CONFIG_PRINTK=y

CONFIG_GPIO=y
CONFIG_I2C=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_CHARGER=y
CONFIG_CHARGER_BQ24295=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y

CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_PICOLIBC=y
CONFIG_REQUIRES_FULL_LIBC=y
