# Generated Zephyr Project Configuration
CONFIG_PRINTK=y
# Target MCU: esp32s3
CONFIG_GPIO=y

# Routing console output via picolibc
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y

CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_PICOLIBC=y
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_REQUIRES_FULL_LIBC=y